services:
  frontend:
    image: rse-frontend:latest
    build:
      context: ./web-view
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: rse-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    restart: always

volumes:
  mongodb-data: