import { useRef, useState } from "react";
import { useAppContext } from "../../hooks/useAppContext";
import type { CsvImportOptions } from "../../types/csvImport";
import { parseCsvTextToDataset } from "../../lib/csvParse";
import { parseOwlToOntology } from "../../lib/owlParse";
import CsvImportDialog from "../CsvImportDialog";
import LoadingComponent from "../UI-NoPurpose/LoadingComp";

export default function WorkspaceImportExport() {
  const { setOntology, setDataset } = useAppContext();
  const [csvDialogOpen, setCsvDialogOpen] = useState(false);
  const [pendingCsvFile, setPendingCsvFile] = useState<File | null>(null);
  const [importingLabel, setImportingLabel] = useState<string | null>(null);
  const csvInputRef = useRef<HTMLInputElement>(null);
  const owlInputRef = useRef<HTMLInputElement>(null);

  const handleCsvFileSelect = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;
    setPendingCsvFile(file);
    setCsvDialogOpen(true);
    if (csvInputRef.current) csvInputRef.current.value = "";
  };

  const handleCsvImportConfirm = (options: CsvImportOptions) => {
    const file = pendingCsvFile;
    if (!file) return;

    setImportingLabel("Importing CSV...");
    const reader = new FileReader();
    reader.onload = (e) => {
      const text = e.target?.result as string;
      const dataset = parseCsvTextToDataset(text, file.name, options);
      if (dataset) setDataset(dataset);
      setImportingLabel(null);
    };
    reader.onerror = () => setImportingLabel(null);
    reader.readAsText(file, options.charset);
    setCsvDialogOpen(false);
    setPendingCsvFile(null);
  };

  const handleOwlImport = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    setImportingLabel("Importing ontology...");
    const reader = new FileReader();
    reader.onload = (e) => {
      const text = e.target?.result as string;
      setOntology(parseOwlToOntology(text, file.name));
      setImportingLabel(null);
    };
    reader.onerror = () => setImportingLabel(null);
    reader.readAsText(file);
    if (owlInputRef.current) owlInputRef.current.value = "";
  };

  const handleExportTtl = () => {
    const ttlContent = `@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .

# RDF Schema Mapping Export
# Generated by RDF Schema Editor
`;
    const blob = new Blob([ttlContent], { type: "text/turtle" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "mapping.ttl";
    a.click();
    URL.revokeObjectURL(url);
  };

  const actionClass =
    "text-gray-500 hover:text-gray-900 transition-colors disabled:opacity-40 dark:hover:text-gray-200";

  return (
    <div className="flex items-center gap-3 px-3 py-1 text-xs border-b border-gray-200 dark:border-gray-800">
      <span className="text-gray-500 select-none dark:text-gray-600">import</span>
      <button
        type="button"
        onClick={() => csvInputRef.current?.click()}
        className={actionClass}
      >
        csv
      </button>
      <button
        type="button"
        onClick={() => owlInputRef.current?.click()}
        className={actionClass}
      >
        owl
      </button>
      <span className="text-gray-300 dark:text-gray-700">|</span>
      <span className="text-gray-500 select-none dark:text-gray-600">export</span>
      <button type="button" onClick={handleExportTtl} className={actionClass}>
        ttl
      </button>

      <input
        ref={csvInputRef}
        type="file"
        accept=".csv"
        aria-label="CSV importieren"
        onChange={handleCsvFileSelect}
        className="hidden"
      />
      <input
        ref={owlInputRef}
        type="file"
        accept=".owl,.rdf,.xml"
        aria-label="OWL importieren"
        onChange={handleOwlImport}
        className="hidden"
      />

      <CsvImportDialog
        isOpen={csvDialogOpen}
        file={pendingCsvFile}
        onClose={() => {
          setCsvDialogOpen(false);
          setPendingCsvFile(null);
        }}
        onConfirm={handleCsvImportConfirm}
      />
      {importingLabel && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-white/80 backdrop-blur-sm dark:bg-gray-950/80">
          <LoadingComponent label={importingLabel} />
        </div>
      )}
    </div>
  );
}
