import { useRef, useState } from "react";
import { Check, Cloud, Loader2 } from "lucide-react";
import { useFileImport } from "../FileImport/FileImportContext";
import { useWorkspace } from "../../hooks/useWorkspace";
import { useLoginContext } from "../../api/LoginInfo";
import OwlImportDialog from "../OwlImportDialog";
import WorkspaceSaveErrorToast from "./WorkspaceSaveErrorToast";

export default function WorkspaceImportExport() {
  const { importFiles, importOntologyFromContent } = useFileImport();
  const { loginInfo } = useLoginContext();
  const { activeWorkspaceId, activeWorkspace, saveWorkspace, savingWorkspaceId } =
    useWorkspace();
  const csvInputRef = useRef<HTMLInputElement>(null);
  const owlInputRef = useRef<HTMLInputElement>(null);
  const [owlDialogOpen, setOwlDialogOpen] = useState(false);
  const [justSavedId, setJustSavedId] = useState<string | null>(null);

  const isSaving = savingWorkspaceId === activeWorkspaceId;
  const isLoggedIn = Boolean(loginInfo);

  const handleSave = async () => {
    if (!activeWorkspaceId) return;
    try {
      await saveWorkspace(activeWorkspaceId);
      setJustSavedId(activeWorkspaceId);
      setTimeout(() => setJustSavedId(null), 2000);
    } catch {
      // saveError from context already reflects the failure
    }
  };

  const handleFileSelect = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;
    importFiles([file]);
    event.target.value = "";
  };

  const handleExportTtl = () => {
    const ttlContent = `@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .

# RDF Schema Mapping Export
# Generated by RDF Schema Editor
`;
    const blob = new Blob([ttlContent], { type: "text/turtle" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "mapping.ttl";
    a.click();
    URL.revokeObjectURL(url);
  };

  const actionClass =
    "text-gray-500 hover:text-gray-900 transition-colors disabled:opacity-40 dark:hover:text-gray-200";

  return (
    <div className="flex items-center gap-3 px-3 py-1 text-xs border-b border-gray-200 dark:border-gray-800">
      <span className="text-gray-500 select-none dark:text-gray-600">import</span>
      <button
        type="button"
        onClick={() => csvInputRef.current?.click()}
        className={actionClass}
      >
        csv
      </button>
      <button
        type="button"
        onClick={() => setOwlDialogOpen(true)}
        className={actionClass}
      >
        owl
      </button>
      <span className="text-gray-300 dark:text-gray-700">|</span>
      <span className="text-gray-500 select-none dark:text-gray-600">export</span>
      <button type="button" onClick={handleExportTtl} className={actionClass}>
        ttl
      </button>

      {isLoggedIn && (
        <>
          <span className="text-gray-300 dark:text-gray-700">|</span>
          <button
            type="button"
            onClick={handleSave}
            disabled={isSaving || !activeWorkspaceId}
            title={
              activeWorkspace?.savedAt
                ? `Zuletzt gespeichert: ${new Date(activeWorkspace.savedAt).toLocaleString("de-DE")}`
                : "Aktuellen Workspace im Account speichern"
            }
            className={`flex items-center gap-1 ${actionClass}`}
          >
            {isSaving ? (
              <Loader2 size={12} className="animate-spin" />
            ) : justSavedId === activeWorkspaceId ? (
              <Check size={12} />
            ) : (
              <Cloud size={12} />
            )}
            save
          </button>
        </>
      )}

      <WorkspaceSaveErrorToast />

      <input
        ref={csvInputRef}
        type="file"
        accept=".csv"
        aria-label="CSV importieren"
        onChange={handleFileSelect}
        className="hidden"
      />
      <input
        ref={owlInputRef}
        type="file"
        accept=".owl,.rdf,.xml"
        aria-label="OWL importieren"
        onChange={handleFileSelect}
        className="hidden"
      />

      <OwlImportDialog
        isOpen={owlDialogOpen}
        onClose={() => setOwlDialogOpen(false)}
        onImportFromFile={() => owlInputRef.current?.click()}
        onImportFromContent={importOntologyFromContent}
      />
    </div>
  );
}
